#!/usr/bin/env python3
"""Validate feature pickle files generated by script/SpectraFeatures.py."""

import argparse
import pickle
from typing import Any, Dict, Iterable, List, Tuple

try:
    import numpy as np
except ModuleNotFoundError:
    raise SystemExit("numpy is required to read and validate this pickle file.")


META_KEY = "__meta__"


def unwrap_entry(value: Any) -> Any:
    if isinstance(value, dict) and "model_input" in value:
        return value.get("model_input")
    return value


def detect_mode(values: Iterable[Any]) -> str:
    for value in values:
        value = unwrap_entry(value)
        if value is None:
            continue
        if not isinstance(value, (list, tuple)) or len(value) != 2:
            continue
        first = np.asarray(value[0])
        second = np.asarray(value[1])
        if first.ndim == 2 and first.shape[0] == 3 and second.ndim == 1:
            return "cnn"
        if first.ndim == 2 and second.ndim == 2 and first.shape[1] == 2 and second.shape[1] == 2:
            return "att"
    return "unknown"


def _finite_check(array: np.ndarray, label: str, errors: List[str]) -> None:
    if not np.isfinite(array).all():
        errors.append(f"{label} has NaN/Inf values.")


def validate_cnn_entry(
    key: str,
    value: Any,
    expected_len: int,
    expected_add_len: int,
) -> Tuple[List[str], List[str], Dict[str, float]]:
    errors: List[str] = []
    warnings: List[str] = []
    stats: Dict[str, float] = {}

    if not isinstance(value, (list, tuple)) or len(value) != 2:
        return [f"{key}: entry is not [xFeatures, X_add_feature]."], warnings, stats

    try:
        x_features = np.asarray(value[0], dtype=float)
    except Exception as exc:
        return [f"{key}: xFeatures cannot be converted to float array ({exc})."], warnings, stats

    try:
        x_add = np.asarray(value[1], dtype=float)
    except Exception as exc:
        return [f"{key}: X_add_feature cannot be converted to float array ({exc})."], warnings, stats

    if x_features.ndim != 2:
        errors.append(f"{key}: xFeatures must be 2D, got ndim={x_features.ndim}.")
    else:
        if x_features.shape[0] != 3:
            errors.append(f"{key}: xFeatures first dimension must be 3, got {x_features.shape[0]}.")
        if expected_len > 0 and x_features.shape[1] != expected_len:
            errors.append(
                f"{key}: xFeatures second dimension should be {expected_len}, got {x_features.shape[1]}."
            )
        stats["pair_count"] = float(x_features.shape[1])
        non_zero = np.count_nonzero(np.any(np.abs(x_features) > 0, axis=0))
        stats["non_zero_pairs"] = float(non_zero)
        _finite_check(x_features, f"{key}: xFeatures", errors)

    if x_add.ndim != 1:
        errors.append(f"{key}: X_add_feature must be 1D, got ndim={x_add.ndim}.")
    else:
        if expected_add_len > 0 and x_add.shape[0] != expected_add_len:
            errors.append(
                f"{key}: X_add_feature length should be {expected_add_len}, got {x_add.shape[0]}."
            )
        _finite_check(x_add, f"{key}: X_add_feature", errors)
        if x_add.shape[0] >= 3:
            charge_one_hot = x_add[-3:]
            if not np.all(np.isin(charge_one_hot, [0.0, 1.0])):
                warnings.append(f"{key}: charge one-hot tail contains values outside {{0,1}}.")
            if not np.isclose(charge_one_hot.sum(), 1.0):
                warnings.append(
                    f"{key}: charge one-hot tail sums to {charge_one_hot.sum():.3f}, expected 1.0."
                )

    return errors, warnings, stats


def validate_att_entry(
    key: str,
    value: Any,
) -> Tuple[List[str], List[str], Dict[str, float]]:
    errors: List[str] = []
    warnings: List[str] = []
    stats: Dict[str, float] = {}

    if not isinstance(value, (list, tuple)) or len(value) != 2:
        return [f"{key}: entry is not [Xexp, Xtheory]."], warnings, stats

    try:
        x_exp = np.asarray(value[0], dtype=float)
    except Exception as exc:
        return [f"{key}: Xexp cannot be converted to float array ({exc})."], warnings, stats

    try:
        x_theory = np.asarray(value[1], dtype=float)
    except Exception as exc:
        return [f"{key}: Xtheory cannot be converted to float array ({exc})."], warnings, stats

    for arr, name in ((x_exp, "Xexp"), (x_theory, "Xtheory")):
        if arr.ndim != 2:
            errors.append(f"{key}: {name} must be 2D, got ndim={arr.ndim}.")
            continue
        if arr.shape[1] != 2:
            errors.append(f"{key}: {name} second dimension must be 2, got {arr.shape[1]}.")
        _finite_check(arr, f"{key}: {name}", errors)

    if x_exp.ndim == 2:
        stats["exp_count"] = float(x_exp.shape[0])
    if x_theory.ndim == 2:
        stats["theory_count"] = float(x_theory.shape[0])

    return errors, warnings, stats


def format_float(x: float) -> str:
    if np.isclose(x, round(x)):
        return str(int(round(x)))
    return f"{x:.3f}"


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate generated spectral feature pickle.")
    parser.add_argument(
        "-i",
        "--input",
        default="test/pct1.pkl",
        help="Path to .pkl file generated by script/SpectraFeatures.py",
    )
    parser.add_argument(
        "-m",
        "--mode",
        choices=["auto", "cnn", "att"],
        default="auto",
        help="Validation schema to apply.",
    )
    parser.add_argument(
        "--max-entries",
        type=int,
        default=0,
        help="Validate only first N entries (0 means all).",
    )
    parser.add_argument(
        "--expected-pair-length",
        type=int,
        default=500,
        help="Expected CNN xFeatures second dimension.",
    )
    parser.add_argument(
        "--expected-additional-length",
        type=int,
        default=11,
        help="Expected CNN X_add_feature length.",
    )
    parser.add_argument(
        "--show-errors",
        type=int,
        default=20,
        help="Maximum number of error/warning lines to print for each category.",
    )
    args = parser.parse_args()

    try:
        with open(args.input, "rb") as fh:
            data = pickle.load(fh)
    except FileNotFoundError:
        print(f"ERROR: file not found: {args.input}")
        return 2
    except Exception as exc:
        print(f"ERROR: failed to load pickle: {exc}")
        return 2

    if not isinstance(data, dict):
        print(f"ERROR: expected dict at top level, got {type(data).__name__}.")
        return 2
    if len(data) == 0:
        print("ERROR: pickle dictionary is empty.")
        return 2

    entries = data
    if META_KEY in data and isinstance(data[META_KEY], dict):
        entries = {k: v for k, v in data.items() if k != META_KEY}
    if len(entries) == 0:
        print("ERROR: pickle dictionary contains no feature entries.")
        return 2

    mode = args.mode
    if mode == "auto":
        mode = detect_mode(entries.values())
        if mode == "unknown":
            print("ERROR: could not auto-detect mode. Use --mode cnn or --mode att.")
            return 2

    errors: List[str] = []
    warnings: List[str] = []
    pair_counts: List[float] = []
    non_zero_counts: List[float] = []
    exp_counts: List[float] = []
    theory_counts: List[float] = []

    print(f"Validating {args.input}")
    print(f"Mode: {mode}")
    print(f"Total entries in pickle: {len(entries)}")

    checked = 0
    for key, value in entries.items():
        if args.max_entries > 0 and checked >= args.max_entries:
            break

        value = unwrap_entry(value)
        if value is None:
            warnings.append(f"{key}: entry has no model_input payload.")
            checked += 1
            continue

        if mode == "cnn":
            e, w, stats = validate_cnn_entry(
                str(key),
                value,
                args.expected_pair_length,
                args.expected_additional_length,
            )
            pair_counts.extend([stats["pair_count"]] if "pair_count" in stats else [])
            non_zero_counts.extend([stats["non_zero_pairs"]] if "non_zero_pairs" in stats else [])
        else:
            e, w, stats = validate_att_entry(str(key), value)
            exp_counts.extend([stats["exp_count"]] if "exp_count" in stats else [])
            theory_counts.extend([stats["theory_count"]] if "theory_count" in stats else [])

        errors.extend(e)
        warnings.extend(w)
        checked += 1

    print(f"Entries checked: {checked}")

    if mode == "cnn" and pair_counts:
        pair_arr = np.asarray(pair_counts)
        nz_arr = np.asarray(non_zero_counts) if non_zero_counts else np.asarray([0.0])
        print(
            "xFeatures pair_count min/mean/max: "
            f"{format_float(pair_arr.min())}/{format_float(pair_arr.mean())}/{format_float(pair_arr.max())}"
        )
        print(
            "xFeatures non_zero_pairs min/mean/max: "
            f"{format_float(nz_arr.min())}/{format_float(nz_arr.mean())}/{format_float(nz_arr.max())}"
        )
    elif mode == "att" and exp_counts and theory_counts:
        exp_arr = np.asarray(exp_counts)
        th_arr = np.asarray(theory_counts)
        print(
            "Xexp count min/mean/max: "
            f"{format_float(exp_arr.min())}/{format_float(exp_arr.mean())}/{format_float(exp_arr.max())}"
        )
        print(
            "Xtheory count min/mean/max: "
            f"{format_float(th_arr.min())}/{format_float(th_arr.mean())}/{format_float(th_arr.max())}"
        )

    if warnings:
        print(f"\nWarnings: {len(warnings)}")
        for line in warnings[: max(args.show_errors, 0)]:
            print(f"- {line}")
        if len(warnings) > args.show_errors:
            print(f"- ... ({len(warnings) - args.show_errors} more warnings)")
    else:
        print("\nWarnings: 0")

    if errors:
        print(f"\nErrors: {len(errors)}")
        for line in errors[: max(args.show_errors, 0)]:
            print(f"- {line}")
        if len(errors) > args.show_errors:
            print(f"- ... ({len(errors) - args.show_errors} more errors)")
        return 2

    print("\nErrors: 0")
    print("Validation passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
